<?php include "header.php" ?>

<div class="aviso-privacidad">
    <h2>Aviso de Privacidad</h2>
    <span class="strong-black curve-span">Curveball Sports & Entertainment</span>
    <p>Curveball Sports & Entertainment (en adelante la “Curveball”) con domicilio en Av. Arboledas No. 101, Col. San Mateo Otzacatipan, C.P. 50200, Toluca, Estado de México, México y correo: <a>contacto@curveball.mx</a> , es el responsable del uso y protección de sus datos personales, y al respecto le informamos:</p>
    <h4>¿Para qué fines utilizamos su información?</h4>
    <p>Los datos personales que recopilamos de usted, los utilizaremos para las siguientes finalidades que son necesarias para el servicio que solicita:</p>
    <ul>
        <li><span class="strong-black">Finalidad Principal A.</span> Con fines de elaborar registros electrónicos y físicos que de acuerdo a su calidad y categoría correspondan para integrar expedientes de las acciones que se lleven a cabo por razón de su desempeño como candidato y/o afiliado a la Youth Cup México.</li>
        <li><span class="strong-black">Finalidad Principal B.</span> Con fines de identificación para contacto vía telefónica o vía correo electrónico; agendar citas, cambios y ubicación de citas; proporcionar información sobre los resultados de partidos practicados, elaboración de órdenes de servicio, facturas, recibos y expedientes personales, así como dar a conocer servicios o procesos de operación al personal y/o miembros registrados.</li>
    </ul>
    <p>De manera adicional utilizaremos su información personal para las siguientes finalidades que no son necesarias para el servicio solicitado pero que nos permiten y facilitan brindarle una mejor atención:</p>
    <ul>
        <li><span class="strong-black">Finalidad Secundaria A.</span>. Con el fin de evaluar la calidad del servicio técnico o administrativo brindado, realizar análisis estadísticos y actividades afines a la Youth Cup México.</li>
        <li><span class="strong-black">Finalidad Secundaria B.</span> Con el fin de promocionar y ofrecer productos o servicios adicionales: eventos, campamentos, conferencias y/o enviar comunicados o boletines.</li>
    </ul>
    <p>En caso que no desee que sus datos personales sean tratados para estos fines, desde este momento usted nos puede comunicar lo anterior y abstenerse de proporcionar datos personales acompañando dicha abstención por escrito libre dirigido a la dirección electrónica: <a href="">contacto@curveball.mx</a> o física citada al inicio del presente Aviso de Privacidad, en los términos que se detallan más adelante para el ejercicio de los derechos ARCO que le asisten como Titular. La negativa para el uso de sus datos personales para fines adicionales, no podrá ser motivo para entregarle los servicios solicitados o dar por terminada la relación establecida con nosotros.</p>
    <h4>¿Qué datos personales utilizaremos para estos fines?</h4>
    <p>Para llevar las finalidades descritas en el presente aviso de privacidad, utilizaremos los siguientes datos personales que usted libre y voluntariamente proporcione a Curveball a través de este website y/o a través de otros medios y distintos formularios que podrán incluir: su nombre, fecha de nacimiento, edad, sexo, estado civil, ocupación, dirección, teléfonos de contacto, referencia/equipo, categoría/división, correo electrónico, nombre del padre o tutor (en caso de menores de edad), identificación oficial, RFC, CURP y comprobante de domicilio.</p>
    <p>Además de los datos personales mencionados anteriormente, para las finalidades informadas en el presente aviso de privacidad utilizaremos los siguientes datos personales considerados como sensibles, que requieren de especial protección como aquéllos que refieren a la fecha del último examen médico general, estado pasado y presente de salud, estado pasado y presente de tratamientos médicos, número de hospitalizaciones y sus causas, alergias, tipo de sangre, antecedentes heredo familiares, antecedentes personales patológicos y no patológicos, así como un interrogatorio de salud y en su caso lectura de estudios médicos por aparatos y sistemas del cuerpo humano. De conformidad con lo que establece el artículo 9 de la Ley en cita, requerimos de su consentimiento expreso para el tratamiento de sus datos personales sensibles, por lo que le solicitaremos en su momento nos indique expresamente si acepta o no el tratamiento de sus datos personales.</p>
    <h4>¿Con quién compartimos su información personal y para que fines?</h4>
    <p>Le informamos que sus datos personales podrán ser compartidos dentro y fuera del país con las siguientes personas, empresas, organizaciones y autoridades distintas a nosotros debido a la naturaleza del objeto social de Curveball y la Youth Cup México; en ese sentido, su información puede ser compartida o proporcionada a:</p>
    <ul>
        <li>FC Bayern Munich (Equipo afiliado a la FIFA)</li>
        <li>Organismos y clubes afines a Bayern Munich </li>
        <li>Organismos afiliados a Curveball</li>
        <li>Asociaciones nacionales e internacionales afiliadas a la FIFA</li>
        <li>World Anti-Doping Agency (WADA)</li>
        <li>Tribunal de Arbitraje Deportivo (TAS)</li>
        <li>El Sistema Nacional de Cultura Física y Deporte (SINADE)</li>
        <li>La Comisión Nacional de Cultura Física y Deporte (CONADE)</li>
        <li>La Confederación Deportiva Mexicana, A.C. (CODEME)</li>
        <li>El Comité Olímpico Mexicano, A.C. (COM)</li>
        <li>Así como todo aquel afiliado a los mencionados y a todos aquellos que por razones propias de sus actividades se relacionen con estas como Laboratorios de Análisis Clínicos, Centros de Salud, Hospitales, Aseguradoras, Agencias de Viaje, Líneas Aéreas, Hoteles, Centros de Alojamiento y Embajadas</li>
    </ul>
    <p>Curveball podrá revelar o permitir el acceso a los Datos Personales que usted nos proporcione para los siguientes fines: <br> a) para cumplir con la legislación aplicable <br> b) por requerimiento de autoridad competente<br> c) sin fines comerciales podrá compartir o transmitir sus datos personales con personas que le provean servicios necesarios para su debida operación así como instituciones subsidiarias o filiales para los mismos fines, en cuyo caso , el tercero receptor asumirá las mismas obligaciones que correspondan al “Responsable” que transfirió los datos. En adición, Curveball podrá contratar a uno o varios terceros como proveedores de servicios seleccionados para manejar y administrar tanto este Portal como los Datos Personales que se recaba a través de éste, o de cualquier otro medio distinto, por lo que podría incluso transferirlos a dicho(s) tercero(s) sin un fin comercial, sino únicamente para cumplir con la prestación de los servicios antes descritos. En ningún caso comercializaremos, venderemos o rentaremos información personal sobre usted a un tercero sin su consentimiento previo. Si usted no manifiesta su negativa para dichas transferencias, entenderemos que nos lo ha otorgado.</p>
    <p>Los Datos Personales que usted proporcione a Curveball podrán compilarse y fijarse en una base de datos propiedad exclusiva de Curveball. Se hace la advertencia que Curveball puede utilizar "cookies" para confirmar su identificación, personalizar su acceso a este Portal y revisar su uso, con el solo propósito de mejorar su navegación y sus condiciones de funcionalidad, toda vez que mediante las citadas “cookies” no se recaban datos personales de los usuarios en términos de la Ley. Este Portal tiene ligas a otros sitios externos, de los cuales el contenido y políticas de privacidad no son responsabilidad de Curveball, por lo que el usuario, en su caso, quedará sujeto a las políticas de privacidad de aquellos otros sitios, sin responsabilidad alguna a cargo de Curveball; entenderemos que usted ha otorgado su consentimiento para el tratamiento y transferencia de sus Datos Personales de conformidad con el presente Aviso de Privacidad si usted no manifiesta su oposición a través de los medios hechos de su conocimiento en este Aviso de Privacidad.</p>
    <h4>¿Qué medidas de seguridad y control utilizamos para la protección de sus Datos Personales?</h4>
    <p>Curveball tiene implementadas medidas de seguridad administrativas, técnicas y físicas para proteger sus Datos Personales contra daño, pérdida, alteración, destrucción, uso, acceso o tratamiento no autorizado, mismas que igualmente exigimos sean cumplidas por los proveedores de servicios que contratamos, aún tratándose de servicios que prestan las empresas subsidiarias o afiliadas a Curveball.</p>
    <h4>¿Cómo puede usted acceder, rectificar o cancelar sus datos personales, u oponerse a su uso?</h4>
    <p>En cualquier momento usted tiene derecho a conocer qué datos personales tenemos de usted, para qué los utilizamos y las condiciones del uso que les damos (Acceso). Asimismo, es su derecho solicitar la corrección de su información personal en caso de que esté desactualizada, sea inexacta o incompleta (Rectificación); que la eliminemos de nuestros registros o bases de datos cuando considere que la misma no está siendo utilizada conforme a los principios, deberes y obligaciones previstas en la normativa (Cancelación); así como oponerse al uso de sus datos personales para fines específicos (Oposición). Estos derechos se conocen como derechos ARCO.</p>
    <p>Para el ejercicio de cualquiera de los derechos ARCO, usted deberá presentar la solicitud respectiva a través del correo electrónico: <a href="">contacto@curveball.mx</a> o personalmente llenando el formato gratuito respectivo en el Departamento de Seguridad de la Información con domicilio en Paseo de la Reforma 915, Lomas de Chapultepec, Miguel Hidalgo 11000, Ciudad de México, México en ambos casos es necesario que acredite su personalidad anexando una copia de cualquier identificación oficial con fotografía a su solicitud; además la solicitud deberá contener por lo menos: (a) nombre y domicilio u otro medio para comunicarle la respuesta a su solicitud; (b) los documentos que acrediten la identidad o, en su caso, la representación legal; (c) la descripción clara y precisa de los Datos Personales respecto de los que se solicita ejercer alguno de los derechos ARCO; y (d) cualquier otro elemento que facilite la localización de los Datos Personales.</p>
    <p> Para conocer a detalle el procedimiento y requisitos para el ejercicio de los derechos ARCO, usted podrá llamar al siguiente número telefónico en horarios de oficina (lunes a viernes de 8 am a 5 pm): <span class="strong-black">52 461 104 3805 </span> o bien ponerse en contacto con nuestra Área de Seguridad de la Información, que dará trámite a las solicitudes para el ejercicio de estos derechos, y atenderá cualquier duda que pudiera tener respecto al tratamiento de su información; los datos de contacto del Área de Seguridad de la Información son: Paseo de la Reforma 915, Lomas de Chapultepec, Miguel Hidalgo 11000, Ciudad de México, México electrónico <a href="">contacto@curveball.mx</a>.</p>
    <h4>¿Cómo puede revocar su consentimiento para el uso de sus datos personales?</h4>
    <p>Usted puede revocar el consentimiento que, en su caso, nos haya otorgado para el tratamiento de sus datos personales. Sin embargo, es importante que tenga en cuenta que no en todos los casos podremos atender su solicitud o concluir el uso de forma inmediata, ya que es posible que por alguna obligación legal requiramos seguir tratando sus datos personales. Asimismo, usted deberá considerar que para ciertos fines, la revocación de su consentimiento implicará que no poder seguir prestando el servicio que nos solicitó, o la concluir su relación con nosotros.</p>
    <p>Para revocar su consentimiento deberá presentar su solicitud a través del correo: <a href="">contacto@curveball.mx</a> o personalmente llenando el formato gratuito respectivo en el Departamento de Seguridad de la Información con domicilio en Paseo de la Reforma 915, Lomas de Chapultepec, Miguel Hidalgo 11000, Ciudad de México, México, en ambos casos es necesario que acredite su personalidad anexando una copia de cualquier identificación oficial con fotografía a su solicitud.</p>
    <p>Para conocer el procedimiento y requisitos para la revocación del consentimiento, usted podrá llamar al siguiente número telefónico en horarios de oficina (lunes a viernes de 8 am a 5 pm): <span class="strong-black">52 461 104 3805 </span> , o bien ponerse en contacto con nuestro Departamento de Seguridad de la Información que dará trámite a las solicitudes para el ejercicio de estos derechos, y atenderá cualquier duda que pudiera tener respecto al tratamiento de su información. Los datos de contacto del Área de Seguridad de la Información son los siguientes: Paseo de la Reforma 915, Lomas de Chapultepec, Miguel Hidalgo 11000, Ciudad de México, México, teléfono 52 461 104 3805 y correo electrónico: <a href="">contacto@curveball.mx</a></p>
    <h4>¿Cómo puede limitar el uso o divulgación de su información personal?</h4>
    <p>Con objeto de que usted pueda limitar el uso y divulgación de su información personal, le ofrecemos los siguientes medios:</p>
    <ol>
        <li>Su inscripción en el Registro Público para Evitar Publicidad, que está a cargo de la Procuraduría Federal del Consumidor, con la finalidad de que sus datos personales no sean utilizados para recibir publicidad o promociones de empresas de bienes o servicios. Para mayor información sobre este registro, usted puede consultar el portal de Internet de la PROFECO, o bien ponerse en contacto directo con ésta.</li>
        <li>Su registro en el listado de exclusión “listado de exclusión”, a fin de que sus datos personales no sean tratados para fines mercadotécnicos, publicitarios o de prospección comercial por nuestra parte. Para mayor información llamar al siguiente número telefónico de <span class="strong-black">52 461 104 3805 </span>, que dará trámite a las solicitudes para el ejercicio de estos derechos, y atenderá cualquier duda que pudiera tener respecto al tratamiento de su información. Los datos de contacto del Área de Seguridad de la Información son: Paseo de la Reforma 915, Lomas de Chapultepec, Miguel Hidalgo 11000, Ciudad de México, México, teléfono 52 461 104 3805 y correo electrónico <a href="">contacto@curveball.mx</a>.</li>
    </ol>
    <h4>El uso de tecnologías de rastreo en nuestro portal de Internet</h4>
    <p>Le informamos que en nuestra página de Internet utilizamos cookies, web beacons y otras tecnologías a través de las cuales es posible monitorear su comportamiento como usuario de Internet, así como brindarle un mejor servicio y experiencia de usuario al navegar en nuestra página; mediante las citadas “cookies” no se recaban datos personales de los usuarios en términos de la Ley. Este website tiene ligas a otros sitios externos, de los cuales el contenido y políticas de privacidad no son responsabilidad de Curveball, por lo que el usuario, en su caso, quedará sujeto a las políticas de privacidad de aquellos otros sitios, sin responsabilidad alguna a cargo de Curveball.</p>
    <p>Entenderemos que usted ha otorgado su consentimiento para el tratamiento y transferencia de sus Datos Personales de conformidad con el presente Aviso de Privacidad; si usted no manifiesta su oposición a través de los medios hechos de su conocimiento en este Aviso.</p>
    <h4>¿Cómo puede conocer los cambios a este aviso de privacidad?</h4>
    <p>El presente aviso de privacidad puede sufrir modificaciones, cambios o actualizaciones derivadas de nuevos requerimientos legales; de nuestras propias necesidades por lo productos o servicios que ofrecemos; de nuestras prácticas de privacidad; de cambios en nuestro modelo de operación, o por otras causas. Nos comprometemos a mantenerlo informado sobre los cambios que pueda sufrir el presente aviso de privacidad, a través de esta página <a href="http://curveball.mx.">http://curveball.mx</a>.</p>
    <p>El procedimiento a través del cuál se llevarán a cabo las notificaciones sobre cambios o actualizaciones al presente aviso de privacidad es mediante la publicación simple del aviso de privacidad en su modalidad integral en la página <a href="http://curveball.mx.">http://curveball.mx</a> sección [Aviso de Privacidad].</p>
    <p>Este Aviso de Privacidad cumple con los requisitos que marca la Ley y el Reglamento.</p>
</div>

<?php include "newsletter.php" ?>

<?php include "footer.php" ?>

<?php include "modal.php" ?>